title: Dennis Jakob
description: Software Developer | Technical Artist
baseurl: ""

theme: cvless

# site settings
taglong: Software Developer | Technical Artist
tagshort: Software Dev | Technical Artist

# author settings
author:
  name: Dennis Jakob
  email: denjako@web.de
photo: assets/files/photo.jpg
address: Bergisch Gladbach, Deutschland

# profile links
profile:
  linkedin: https://www.linkedin.com/in/dennis-jakob-b177502b7/
  xing: https://www.xing.com/profile/Dennis_Jakob10
  github: https://github.com/denjkob

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-sitemap

sass:
  sourcemap: never
  
pagination:
  enabled: true
  debug: true
  per_page: 3
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
