title: Dennis Jakob
description: Software Developer | Technical Artist
baseurl: ""
url: https://denjkob.github.io/

theme: cvless

# site settings
taglong: Software Developer | Technical Artist
tagshort: Software Dev | Technical Artist

# author settings
author:
  name: Dennis Jakob
  email: denjako@web.de
photo: assets/files/photo.jpg
address: Bergisch Gladbach

# profile links
profile:
  bluesky: https://bsky.app/profile/username.bsky.social
  linkedin: https://www.linkedin.com/in/username
  xing: https://www.xing.com/profile/username
  stackoverflow: https://stackoverflow.com/users/0000000/username
  github: https://github.com/username

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-sitemap

sass:
  sourcemap: never
  
pagination:
  enabled: true
  debug: true
  per_page: 3
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
